spring.application.name=electro

# Configuration for Spring Datasource
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:elec}?options=-c%20timezone=UTC
spring.datasource.username=${DB_USERNAME:appuser}
spring.datasource.password=${DB_PASSWORD:apppass}

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Flyway migration settings
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Cloudinary Settings
cloudinary.cloud-name=${CLOUDINARY_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# T?ng gi?i h?n upload file cho ?nh linh ki?n ?i?n t?
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Signer key (HMAC - SHA)
jwt.signerKey=${JWT_SIGNER_KEY:5p7Q9zR2xW4vB8nM1kL6jH3gD0sF9aC2eY4uI1oP7tR5eW3qZ2xS8cM4vN1b0A9}

# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.timeout=2000